# file config/monapp.yml
 
defaults: &defaults
  :secret_key_base: please_change_me_because_i_m_not_safe
 
development:
# we are using standard YML inheritance here, very powerful and native !
  <<: *defaults
  :secret_key_base: i_am_overrided
 
test:
  <<: *defaults
 
production:
  <<: *defaults 